import ollama
import re


def generate_playwright_script(test_cases):

    prompt = f"""
You are a senior QA automation engineer.

Convert the following test cases into Playwright Python pytest automation scripts.

STRICT RULES:
- Return ONLY Python code
- Do NOT include explanations
- Do NOT include text like "Here is the script"
- Code must start with imports
- Use pytest
- Use playwright.sync_api

Test Cases:
{test_cases}
"""

    response = ollama.chat(
        model="deepseek-coder",
        messages=[{"role": "user", "content": prompt}]
    )

    script = response["message"]["content"]

    # Clean markdown if AI returns ```python blocks
    script = script.replace("```python", "").replace("```", "")

    # If the model included prose, extract from the first Python import onward
    m = re.search(r"(^|\n)(from\s+\w+\s+import|import\s+\w+)", script)
    if m:
        script = script[m.start():]

    # Trim anything after the last explicit browser.close() to avoid trailing prose
    last_close = script.rfind("browser.close()")
    if last_close != -1:
        # keep until end of that line
        end_idx = script.find('\n', last_close)
        if end_idx == -1:
            end_idx = len(script)
        script = script[:end_idx+1]

    # Replace invalid Playwright API calls generated by the model with a clear TODO
    script = re.sub(r"page\.is_response_status\([^)]*\)",
                    "assert True  # TODO: replace with proper response/status check",
                    script)

    return script


def save_playwright_script(script):

    file_path = "playwright/tests/test_generated.py"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"Playwright script saved to {file_path}")