import os
import subprocess
import argparse
import json
from datetime import datetime


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)


def save_file(path, content):
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def fallback_test_cases(requirement_text):
    # Very small fallback that creates one test-case summary
    lines = [l.strip() for l in requirement_text.splitlines() if l.strip()]
    title = lines[0] if lines else "Auto-generated test"
    return f"TC-1 | {title} | Steps: 1) Open app | Expected: App loads"


def fallback_playwright_script(test_cases_text):
    # Minimal script that includes self-heal helpers and a placeholder test
    script = (
        "import pytest\n"
        "from playwright.sync_api import sync_playwright\n"
        "from playwright.helpers.self_heal import safe_click, safe_fill\n\n"
        "def test_autogenerated_placeholder():\n"
        "    with sync_playwright() as p:\n"
        "        browser = p.chromium.launch()\n"
        "        page = browser.new_page()\n"
        "        page.set_content('<html><body><h1>placeholder</h1></body></html>')\n"
        "        assert page.locator('h1').inner_text() == 'placeholder'\n"
        "        browser.close()\n"
    )
    return script


def run_agent(requirement_path, mapping_path, out_script_path, run_tests=False):
    # Load inputs
    from loaders.word_loader import load_word_document
    requirement_text = ""
    if os.path.exists(requirement_path):
        requirement_text = load_word_document(requirement_path)
    else:
        raise FileNotFoundError(requirement_path)

    mapping_text = ""
    try:
        from loaders.excel_loader import load_excel_mapping
        if os.path.exists(mapping_path):
            mapping_text = load_excel_mapping(mapping_path)
    except Exception:
        mapping_text = ""

    context = requirement_text + "\n" + mapping_text

    # 1) Generate test cases using AI generator, fallback on error
    test_cases_text = None
    try:
        from ai_engine.test_generator import generate_test_cases
        test_cases_text = generate_test_cases(context)
    except Exception as e:
        print(f"[agent] LLM test generation failed, using fallback: {e}")
        test_cases_text = fallback_test_cases(requirement_text)

    # 2) Generate Playwright script using AI generator, fallback on error
    script_text = None
    try:
        from ai_engine.script_generator import generate_playwright_script
        script_text = generate_playwright_script(test_cases_text)
    except Exception as e:
        print(f"[agent] LLM script generation failed, using fallback: {e}")
        script_text = fallback_playwright_script(test_cases_text)

    # 3) Save the script to output path
    save_file(out_script_path, script_text)
    print(f"[agent] Saved script to {out_script_path}")

    report = {
        'script_path': out_script_path,
        'test_cases': test_cases_text,
        'generated_at': datetime.utcnow().isoformat() + 'Z'
    }

    results_dir = os.path.join('generated', 'reports')
    ensure_dir(results_dir)
    report_json = os.path.join(results_dir, 'last_run_summary.json')
    with open(report_json, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2)

    # 4) Optionally run pytest on the generated script and save junit xml
    if run_tests:
        junit_path = os.path.join(results_dir, 'junit.xml')
        cmd = [
            'py', '-3', '-m', 'pytest', out_script_path,
            '--junitxml=' + junit_path, '-q'
        ]
        env = os.environ.copy()
        # Ensure project root is importable
        env['PYTHONPATH'] = env.get('PYTHONPATH', '.') + os.pathsep + '.'
        print(f"[agent] Running tests: {' '.join(cmd)}")
        proc = subprocess.run(cmd, env=env, capture_output=True, text=True)
        with open(os.path.join(results_dir, 'pytest_stdout.txt'), 'w', encoding='utf-8') as f:
            f.write(proc.stdout)
        with open(os.path.join(results_dir, 'pytest_stderr.txt'), 'w', encoding='utf-8') as f:
            f.write(proc.stderr)
        report['pytest_returncode'] = proc.returncode
        print(f"[agent] Pytest finished with return code {proc.returncode}")

    # 5) Save final summary
    with open(report_json, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2)

    print(f"[agent] Summary saved to {report_json}")
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--requirement', default='data/requirements/requirement.docx')
    parser.add_argument('--mapping', default='data/mappings/api_mapping.xlsx')
    parser.add_argument('--out', default='generated/playwright_tests/test_ai_generated.py')
    parser.add_argument('--run-tests', action='store_true')
    args = parser.parse_args()

    run_agent(args.requirement, args.mapping, args.out, run_tests=args.run_tests)


if __name__ == '__main__':
    main()
